/**
 * 33 个人物的 Q 版造型（按人物 id 取，静态数据，没有随机、没有按 id 哈希挑衣服）。
 * 推导顺序：设定 → 气质 → 特征 → 发型 → 服装 → 配色 → 表情 / 姿态倾向；每个字段标了来源（basis）：
 *   config   = 人物设定里本来就有（visual 的肤色、发色、发型、衣服色、extras，或身份里明写的东西）
 *   inferred = 按设定推断的造型（设定没写，按气质和身份补的）
 *   request  = 按用户的统一要求调整（多种族肤色、没写进设定的发色）
 * 历史设定节选见 docs/archive/art/00-roster.md，当前配置说明见 docs/character-looks.md（由 scripts/gen-looks-doc.mjs 生成）。
 */
import type {Look} from './types';
const C='config' as const,I='inferred' as const,R='request' as const;
export const LOOKS:Record<string,Look>={
  // ———— 情绪陪伴组 ————
  'jie-mo':{id:'jie-mo',name:'芥末',skin:'#f3d2b3',body:{type:'crisp',head:'square',sit:'standard'},hair:{style:'spiky',color:'#a9c150'},
    face:{eyes:'sharp',iris:'#7a5a1a',brows:'sharp',mouth:'flat'},
    top:{kind:'tee',color:'#ece6d2'},outer:{kind:'jacket',color:'#7f8f33',trim:'#4f5a20'},bottom:{kind:'cargo',color:'#3d3a33'},shoes:{kind:'boots',color:'#4a3a2a'},acc:[{kind:'tool',color:'#7f8f33',shape:'wrench'}],
    tendency:{expression:'neutral',gesture:1.2,lean:.08,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'直言担当、指责型，火气基线 2：芥末绿刺猬头（设定发色 + spiky）、上挑的锐眼和压低的眉（设定 brows）；设定的橄榄绿做成一件利落的工装夹克（拉链拉到胸口），配深色工装裤和靴子——“说话冲但只冲问题”的干练感。手势幅度大、坐着微微前倾。'},
  'hao-hao':{id:'hao-hao',name:'好好',skin:'#f6d7bd',body:{type:'petite',head:'oval',sit:'relaxed'},hair:{style:'cloud',color:'#e0b467'},
    face:{eyes:'round',iris:'#4a7aa0',brows:'soft',mouth:'smile',marks:['blush'],style:'anime'},
    top:{kind:'blouse',color:'#f4ecdc'},outer:{kind:'cardigan',color:'#5aa6c9',trim:'#f4ecdc'},bottom:{kind:'skirt',color:'#3e4a66',socks:'#4b5268'},shoes:{kind:'loafers',color:'#3e4458'},
    acc:[{kind:'clip',color:'#f2c84b',side:1},{kind:'ahoge'},{kind:'ribbon',color:'#f2c84b'}],
    tendency:{expression:'neutral',gesture:.9,lean:.1,tilt:.08},
    basis:{skin:C,body:R,hairColor:C,hairStyle:C,eyes:R,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'精修样板 B（2026-10-09 第一轮，未经用户视觉验收）：和冷萃拉开轮廓——小巧型身体（约 3.9 头身，头比 Q 版小很多）、鹅蛋脸、两倍像素的圆圆蓝色动漫眼和一层淡淡的腮红线；蜂蜜色云朵短卷发（设定 curly），刘海是几个圆头小卷，头顶一根呆毛、一枚黄色发夹；米白圆领衬衫系一只蜂蜜黄的领结，外面一件天蓝色粗针开衫（设定衣服色），藏青百褶短裙配藏青灰长袜和深色乐福鞋。外观不按“讨好型”性格推：设定里的露齿笑和汗滴是神态，交给表情系统按情绪出现；“总往前探、头微歪”只体现在姿态倾向里。'},
  'leng-cui':{id:'leng-cui',name:'冷萃',skin:'#e8b98f',body:{type:'elegant',head:'oval',sit:'standard'},hair:{style:'sidelong',color:'#4b3a33',tie:'#e9e1c8'},
    face:{eyes:'sharp',iris:'#6b4a2e',brows:'straight',mouth:'small',style:'anime'},
    top:{kind:'turtleneck',color:'#e9e1c8'},outer:{kind:'coat',color:'#7a5a45',trim:'#5a3f2f'},bottom:{kind:'pants',color:'#3b3230'},shoes:{kind:'boots',color:'#4a3426'},
    acc:[{kind:'roundGlasses',color:'#b8964f'},{kind:'belt',color:'#4a3426'},{kind:'pin',color:'#b8964f',shape:'leaf'}],
    tendency:{expression:'neutral',gesture:.8,lean:0,tilt:0},
    basis:{skin:C,body:R,hairColor:C,hairStyle:C,eyes:R,top:C,outer:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'精修样板 A（2026-10-09 第一轮，未经用户视觉验收）：按“精致 Minecraft 动漫风”重做，外观只锚定设定里的发色、咖啡色主色、米白辅色和眼镜，不按性格推外形。修长型身体（约 4.3 头身、头缩到 0.6）、鹅蛋脸、两倍像素的动漫眼（上挑的眼线、琥珀色渐变虹膜）；侧分长发：一大片刘海扫向右眉，两缕鬓发垂到锁骨，背后长发垂到背中、发梢收成 V 形，两侧发梢往外散，头顶一道天使环高光（不是马尾）；米白高领针织 + 过膝的咖啡色长风衣（翻领、腰带、铜扣）、深色长裤、短靴，细金边圆眼镜、一枚叶形胸针。性格只影响神态和动作（手势收着、坐得端正）。'},
  'fu-du-ji':{id:'fu-du-ji',name:'复读机',skin:'#f1c9a5',body:{type:'bulky',head:'round',sit:'relaxed'},hair:{style:'shaggy',color:'#5b4a3e'},
    face:{eyes:'sleepy',iris:'#5a4a40',brows:'soft',mouth:'small'},
    top:{kind:'hoodie',color:'#7c8190',trim:'#d8d4cc'},bottom:{kind:'pants',color:'#4a4d57'},shoes:{kind:'slippers',color:'#9aa0aa'},acc:[{kind:'hood',color:'#7c8190'},{kind:'waistBag',color:'#7c8190'}],
    tendency:{expression:'neutral',gesture:.6,lean:-.08,tilt:.05},
    basis:{skin:C,body:I,hairColor:C,hairStyle:I,eyes:C,top:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'聊天极简主义者，只回“确实”：设定的 hood 做成真的兜帽戴在头上，灰色卫衣（设定衣服色）、睡眼（设定 sleepy）、小嘴；卫裤 + 拖鞋，整个人往后瘫。手势最小。'},
  'shu-dong':{id:'shu-dong',name:'树洞',skin:'#c68b5e',body:{type:'slim',head:'long',sit:'side'},hair:{style:'curtain',color:'#3a2b26',tuck:true},
    face:{eyes:'droopy',iris:'#4a3020',brows:'soft',mouth:'smile'},
    top:{kind:'tee',color:'#e9e1c8'},outer:{kind:'cardigan',color:'#4b5596',trim:'#e9e1c8'},bottom:{kind:'pants',color:'#5a4a3e'},shoes:{kind:'sneakers',color:'#4a3a30'},acc:[{kind:'earring',color:'#e0c060',side:1},{kind:'necklace',color:'#e0c060',shape:'leaf'}],
    tendency:{expression:'neutral',gesture:.8,lean:.1,tilt:.12},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:C,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'倾听者，“听起来……”：中分（设定 middle），头发别到耳后露出耳朵（设定 extras: ears）、一侧小耳钉；下垂的温柔眼、浅笑；靛蓝开衫（设定衣服色）罩米白 T 恤（设定 accent 色）。坐着前倾、歪头听。'},
  'nuan-bao-bao':{id:'nuan-bao-bao',name:'暖宝宝',skin:'#f3d2b3',body:{type:'cute',head:'round',sit:'side'},hair:{style:'bob',color:'#8a4b32'},
    face:{eyes:'sparkle',iris:'#7a4a2a',brows:'soft',mouth:'cat',marks:['blush']},
    top:{kind:'sweater',color:'#9a4f8e',trim:'#e8a33d'},bottom:{kind:'skirt',color:'#5a3a4a',socks:'#efe2cf'},shoes:{kind:'boots',color:'#6a4a3a'},acc:[{kind:'beanie',color:'#e8a33d'},{kind:'scarf',color:'#d9734a'},{kind:'charm',color:'#d9734a',shape:'heart'}],
    tendency:{expression:'happy',gesture:1,lean:.05,tilt:.1},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'情绪充电宝、暖心型：设定的 beanie（accent 姜黄色）+ scarf 全保留——毛线帽带绒球、橙红围巾垂一条；梅子色毛衣（设定衣服色）、百褶裙 + 长袜 + 短靴；亮晶晶的眼、猫嘴、腮红（设定 happy、blush）。默认表情就是笑。'},
  'pao-zhang':{id:'pao-zhang',name:'炮仗',skin:'#e8a98a',body:{type:'broad',head:'square',sit:'standard'},hair:{style:'flame',color:'#2b2136'},
    face:{eyes:'sharp',iris:'#8a2e22',brows:'thick',mouth:'grin',marks:['blush']},
    top:{kind:'tee',color:'#c0625a',trim:'#f2c14e',pattern:'plain'},bottom:{kind:'shorts',color:'#3a4a6a'},shoes:{kind:'sneakers',color:'#e8a33d'},acc:[{kind:'watch'},{kind:'pin',color:'#e8a33d',shape:'flame'}],
    tendency:{expression:'angry',gesture:1.3,lean:.12,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:I,eyes:I,top:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'一点就炸，火气基线 4：设定只有短发，按“炮仗”推成往上往后炸开的冲天炮发型；粗眉（设定 brows）、锐眼、露齿、脸红（设定 blush）；砖红短袖 T（设定衣服色）+ 短裤 + 引信一样的橙黄球鞋（设定 accent 色），一身随时要冲出去的轻装。默认表情是生气，手势最大、前倾最多。'},
  // ———— 娱乐室友组（设定里只有衣服颜色，造型几乎全是推断） ————
  'ent-affirmer-001':{id:'ent-affirmer-001',name:'阿实',skin:'#f6e3d2',body:{type:'standard',sit:'relaxed'},hair:{style:'tidy',color:'#8a5a3c'},
    face:{eyes:'round',iris:'#3a4a7a',brows:'soft',mouth:'smile'},
    top:{kind:'hoodie',color:'#4A8FD0',trim:'#f4efe4'},bottom:{kind:'pants',color:'#c8b48c'},shoes:{kind:'sneakers',color:'#f0eee8'},acc:[{kind:'ahoge'},{kind:'pin',color:'#4A8FD0',shape:'star'}],
    tendency:{expression:'happy',gesture:1.15,lean:.08,tilt:.04},
    basis:{skin:R,body:I,hairColor:R,hairStyle:I,eyes:I,top:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'最捧场的室友，憨、热心：设定只有短发和蓝色；做成清爽短发 + 一根呆毛（憨）、圆眼、笑嘴；蓝色连帽卫衣（设定衣服色，帽兜堆在背后）+ 卡其裤 + 白球鞋。默认开心，点头幅度大。 肤色和发色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'ent-cold-observer-001':{id:'ent-cold-observer-001',name:'阿冷',skin:'#c4a07a',body:{type:'slim',head:'long',sit:'standard'},hair:{style:'sweep',color:'#2f3a4a'},
    face:{eyes:'narrow',iris:'#4a5560',brows:'straight',mouth:'flat'},
    top:{kind:'turtleneck',color:'#607080'},bottom:{kind:'pants',color:'#2e3440'},shoes:{kind:'boots',color:'#5a4636'},acc:[{kind:'headphones',color:'#c9c4b8'},{kind:'pin',color:'#607080',shape:'mic'}],
    tendency:{expression:'neutral',gesture:.7,lean:-.05,tilt:0},
    basis:{skin:R,body:I,hairColor:R,hairStyle:I,eyes:I,top:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'校园电台编辑、冷面观察者：身份里的“电台”推出一副浅灰的头戴监听耳机；侧分长刘海盖住一边眼睛、细长眼、平眉、抿嘴；灰蓝高领（设定衣服色）+ 深色长裤 + 棕色短靴，冷色里只留耳机和靴子两处亮暗点。动作最克制，稍往后靠。 肤色和发色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'ent-contrarian-001':{id:'ent-contrarian-001',name:'老方',skin:'#a86b45',body:{type:'broad',head:'square',sit:'relaxed'},hair:{style:'quiff',color:'#1c1412',streak:'#c9a14a'},
    face:{eyes:'sharp',iris:'#5a2a2a',brows:'arched',mouth:'smirk'},
    top:{kind:'polo',color:'#C04848',trim:'#f2e6d6'},bottom:{kind:'shorts',color:'#3a3a44'},shoes:{kind:'sneakers',color:'#f0eee8'},acc:[{kind:'watch'},{kind:'pin',color:'#C04848',shape:'cross'}],
    tendency:{expression:'neutral',gesture:1.25,lean:.1,tilt:-.04},
    basis:{skin:R,body:I,hairColor:R,hairStyle:I,eyes:I,top:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'嘴快爱抬杠、理直气壮：往前翘的飞机头（抬杠的“欠”）、挑眉、歪嘴笑；红色 Polo（设定衣服色）领子立着、短裤、手表——一副“我反驳”的随意样子。手势大、前倾。 肤色和发色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'ent-counter-contrarian-001':{id:'ent-counter-contrarian-001',name:'小正',skin:'#f3c7a8',body:{type:'crisp',head:'square',sit:'standard'},hair:{style:'tidy',color:'#3a2a48'},
    face:{eyes:'round',iris:'#4a3a6a',brows:'arched',mouth:'smirk'},
    top:{kind:'shirt',color:'#f4f0e8'},outer:{kind:'cardigan',color:'#8A5AC0',trim:'#f4f0e8'},bottom:{kind:'pants',color:'#3a3448'},shoes:{kind:'loafers',color:'#3a2a2a'},acc:[{kind:'roundGlasses',color:'#3a3448'},{kind:'bowtie',color:'#4a2f70'},{kind:'pin',color:'#8A5AC0',shape:'note'}],
    tendency:{expression:'neutral',gesture:1.1,lean:.06,tilt:.04},
    basis:{skin:R,body:I,hairColor:R,hairStyle:I,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'反反驳型，专跟老方对着干、得意嘴硬：做成老方的反面——规整的侧分、圆框眼镜、白衬衫 + 领结 + 紫色开衫（设定衣服色）、乐福鞋，一副“正经人”样子，但挑眉歪嘴（得意）。 肤色和发色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'ent-imagination-001':{id:'ent-imagination-001',name:'小戏',skin:'#e8b39a',body:{type:'cute',head:'round',sit:'side'},hair:{style:'bob',color:'#8a3a2a',streak:'#e7c27a'},
    face:{eyes:'sparkle',iris:'#8a5a2a',brows:'arched',mouth:'cat'},
    top:{kind:'tee',color:'#f2e8d8',pattern:'stripe'},outer:{kind:'cardigan',color:'#C07040',trim:'#f2e8d8'},bottom:{kind:'pants',color:'#5a4a40'},shoes:{kind:'boots',color:'#4a3a30'},acc:[{kind:'beret',color:'#8a3a2a'},{kind:'pen',color:'#2a2a3a',side:-1},{kind:'charm',color:'#C07040',shape:'mask'}],
    tendency:{expression:'happy',gesture:1.3,lean:.1,tilt:.1},
    basis:{skin:R,body:I,hairColor:R,hairStyle:I,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'话剧社脑洞编剧：贝雷帽 + 耳后一支笔（编剧）、亮晶晶的眼、猫嘴；条纹 T 外面一件橙棕开衫（设定衣服色）、短靴。表情丰富，手势大，歪头。 肤色和发色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'ent-life-friend-001':{id:'ent-life-friend-001',name:'阿禾',skin:'#c47a52',body:{type:'outdoor',sit:'relaxed'},hair:{style:'crew',color:'#4a3424'},
    face:{eyes:'droopy',iris:'#4a5a3a',brows:'soft',mouth:'smile',marks:['freckles']},
    top:{kind:'tee',color:'#f0ead8'},outer:{kind:'overalls',color:'#6A9A5A'},bottom:{kind:'pants',color:'#6A9A5A'},shoes:{kind:'sneakers',color:'#c9b48a'},acc:[{kind:'waistBag',color:'#6A9A5A'}],
    tendency:{expression:'happy',gesture:1,lean:.05,tilt:.06},
    basis:{skin:R,body:I,hairColor:R,hairStyle:I,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'食堂和宿舍楼之间的生活派、随和：寸头、下垂的笑眼、几颗雀斑；绿色背带裤（设定衣服色，“禾”）罩米白 T 恤、帆布鞋——朴素、有生活气。 肤色和发色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'ent-normal-001':{id:'ent-normal-001',name:'小林',skin:'#6e4634',body:{type:'bulky',head:'round',sit:'relaxed'},hair:{style:'shaggy',color:'#6a5a48'},
    face:{eyes:'sleepy',iris:'#4a4a3a',brows:'straight',mouth:'flat'},
    top:{kind:'hoodie',color:'#7A8A70',trim:'#d8d4c4'},bottom:{kind:'shorts',color:'#4a4a4a'},shoes:{kind:'slippers',color:'#8a8a8a'},acc:[{kind:'neckphones',color:'#2a2a2e'},{kind:'charm',color:'#7A8A70',shape:'controller'}],
    tendency:{expression:'neutral',gesture:.7,lean:-.1,tilt:0},
    basis:{skin:R,body:I,hairColor:R,hairStyle:I,eyes:I,top:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'正常人、怕麻烦、惦记着“别耽误开黑”：乱糟糟没打理的中长发、睡眼；灰绿卫衣（设定衣服色）+ 短裤 + 拖鞋，脖子上挂着游戏耳机。最懒散，往后瘫。 肤色和发色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'podcast-host-amai':{id:'podcast-host-amai',name:'阿麦',skin:'#f1c9a5',body:{type:'crisp',sit:'standard'},hair:{style:'sweep',color:'#2b2420'},
    face:{eyes:'round',iris:'#3a3a4a',brows:'straight',mouth:'smile'},
    top:{kind:'shirt',color:'#f4efe2'},outer:{kind:'blazer',color:'#2f4058',trim:'#f4efe2'},bottom:{kind:'pants',color:'#2a2f3a'},shoes:{kind:'loafers',color:'#2a2020'},acc:[{kind:'roundGlasses',color:'#2b2420'},{kind:'headset',color:'#8f3a34'},{kind:'pin',color:'#8f3a34',shape:'mic'}],
    tendency:{expression:'neutral',gesture:.9,lean:.05,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:C,outer:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'访谈播客主持人，用语规范、礼貌：侧分（设定 side）+ 圆框眼镜（设定 glasses）、带麦克风的酒红单耳耳麦（主持身份推断，像录音棚的“on air”红灯）；藏青西装（设定衣服色）+ 白衬衫（设定 accent 色）。端正、手势适中。'},
  // ———— 产品研发组 ————
  'ji-mu':{id:'ji-mu',name:'积木',skin:'#f3d2b3',body:{type:'cute',head:'round',sit:'standard'},hair:{style:'bob',color:'#3d3550'},
    face:{eyes:'sparkle',iris:'#5a4a8a',brows:'soft',mouth:'smile'},
    top:{kind:'tee',color:'#f4efe4',pattern:'stripe'},outer:{kind:'overalls',color:'#8a6fb0'},bottom:{kind:'pants',color:'#8a6fb0'},shoes:{kind:'sneakers',color:'#d4b04c'},acc:[{kind:'beanie',color:'#d4b04c'},{kind:'charm',color:'#d4b04c',shape:'block'}],
    tendency:{expression:'happy',gesture:1.1,lean:.08,tilt:.05},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'需求拆解师，“我先拆一下”：设定的 beanie（金色 accent）保留；紫色背带裤（设定衣服色）+ 条纹 T，像搭积木的工装；亮眼、笑（设定 happy）。'},
  'suan-pan':{id:'suan-pan',name:'算盘',skin:'#f1c9a5',body:{type:'crisp',head:'square',sit:'standard'},hair:{style:'tidy',color:'#2b2136'},
    face:{eyes:'sharp',iris:'#6a5a2a',brows:'straight',mouth:'grin'},
    top:{kind:'shirt',color:'#f4efe4'},outer:{kind:'vest',color:'#d4b04c'},bottom:{kind:'pants',color:'#2b2136'},shoes:{kind:'loafers',color:'#2b2136'},acc:[{kind:'tie',color:'#7a2e2a'},{kind:'watch'},{kind:'pin',color:'#d4b04c',shape:'coin'}],
    tendency:{expression:'neutral',gesture:1.1,lean:.08,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:C,shoes:I,acc:C,palette:C,tendency:C},
    why:'商业操盘手，先算账、敢砍：梳得整齐的侧分（设定 side）、锐眼、露齿笑（设定 grin）；金色马甲（设定衣服色）+ 白衬衫 + 算盘珠一样的枣红领带 + 深色长裤（设定 accent 深色）、手表——精明的生意人。'},
  'fang-da-jing':{id:'fang-da-jing',name:'放大镜',skin:'#f6d7bd',body:{type:'slim',head:'round',sit:'standard'},hair:{style:'curly',color:'#6b4a3a'},
    face:{eyes:'round',iris:'#6a4a3a',brows:'arched',mouth:'small',marks:['blush']},
    top:{kind:'turtleneck',color:'#f2e6d8'},outer:{kind:'coat',color:'#c47a9a',trim:'#8a4a6a'},bottom:{kind:'pants',color:'#4a3a3a'},shoes:{kind:'boots',color:'#5a3a2a'},acc:[{kind:'roundGlasses',color:'#6b4a3a'},{kind:'tool',color:'#6b4a3a',shape:'magnifier'}],
    tendency:{expression:'thinking',gesture:1,lean:.12,tilt:.1},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'用户体验侦探：卷发（设定 curly）、圆框眼镜（设定 glasses）、腮红（设定 blush）；粉色系腰带的侦探风衣（设定衣服色）+ 高领 + 短靴；挑眉、默认在想事情，身体前倾“等等，用户真会这么用吗？”。'},
  'ban-shou':{id:'ban-shou',name:'扳手',skin:'#e8b98f',body:{type:'outdoor',head:'square',sit:'standard'},hair:{style:'crew',color:'#6b6272'},
    face:{eyes:'narrow',iris:'#4a5a4a',brows:'thick',mouth:'flat'},
    top:{kind:'tee',color:'#6f9e6b'},outer:{kind:'apron',color:'#5a4632'},bottom:{kind:'cargo',color:'#4a4a48'},shoes:{kind:'boots',color:'#3a3028'},acc:[{kind:'cap',color:'#2b2136'},{kind:'pen',color:'#d8a03a',side:1},{kind:'goggles',color:'#2b2136'},{kind:'tool',color:'#5a4632',shape:'wrench'}],
    tendency:{expression:'neutral',gesture:.9,lean:.04,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:C,outer:I,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'技术与 AI 工程师，“先说坏了怎么办”：设定的 cap（深色 accent）+ 寸头、粗眉（设定 brows）；绿色 T 恤（设定衣服色）外系一条皮质工具围裙、工装裤、工靴，耳后夹一支铅笔——稳。'},
  'zhao-yao-jing':{id:'zhao-yao-jing',name:'照妖镜',skin:'#f1c9a5',body:{type:'slim',head:'long',sit:'relaxed'},hair:{style:'shaggy',color:'#2b2136'},
    face:{eyes:'sleepy',iris:'#3a4a6a',brows:'straight',mouth:'flat'},
    top:{kind:'hoodie',color:'#5f82b0',trim:'#e9e1c8'},bottom:{kind:'jeans',color:'#2e3a50'},shoes:{kind:'sneakers',color:'#2a2a30'},acc:[{kind:'hood',color:'#3f5a80'},{kind:'glasses',color:'#1e1e24'},{kind:'pin',color:'#5f82b0',shape:'bug'}],
    tendency:{expression:'neutral',gesture:.7,lean:.05,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:I,eyes:C,top:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'数据与安全验证官、红队视角：设定的 hood 做成戴上的深蓝兜帽 + 黑框眼镜（“镜”）、睡眼（设定 sleepy）冷着脸；蓝色卫衣（设定衣服色）+ 牛仔裤。和复读机同是兜帽，靠眼镜、深色兜帽和牛仔裤分开。'},
  'nao-zhong':{id:'nao-zhong',name:'闹钟',skin:'#f1c9a5',body:{type:'crisp',sit:'standard'},hair:{style:'odango',color:'#2b2136',tie:'#c94a3a'},
    face:{eyes:'sharp',iris:'#3a4a6a',brows:'sharp',mouth:'flat'},
    top:{kind:'shirt',color:'#e9e1c8'},outer:{kind:'blazer',color:'#2f4a6b',trim:'#c94a3a'},bottom:{kind:'pants',color:'#2a3240'},shoes:{kind:'loafers',color:'#3a2a2a'},acc:[{kind:'watch'},{kind:'pin',color:'#c94a3a',shape:'clock'}],
    tendency:{expression:'neutral',gesture:1.1,lean:.1,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:C,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'项目经理，到点就响：设定的 bun 做成头顶两个丸子（像闹钟的两只铃），扎红发圈；锐眼、上挑的眉（设定 brows）；藏青西装（设定衣服色，胸袋一角红）+ 米白衬衫（设定 accent）+ 手表。'},
  'pin-tu':{id:'pin-tu',name:'拼图',skin:'#f6d7bd',body:{type:'standard',head:'round',sit:'relaxed'},hair:{style:'spiky',color:'#4a3426'},
    face:{eyes:'round',iris:'#2a6a6a',brows:'soft',mouth:'smile'},
    top:{kind:'hoodie',color:'#3f9e98',trim:'#f4efe4'},bottom:{kind:'jeans',color:'#3a4a6a'},shoes:{kind:'sneakers',color:'#f0eee8'},acc:[{kind:'glasses',color:'#2a2a30'},{kind:'neckphones',color:'#f0eee8'},{kind:'charm',color:'#3f9e98',shape:'puzzle'}],
    tendency:{expression:'neutral',gesture:1,lean:.06,tilt:.04},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'前端工程师，“我先搭个能点的”：刺猬头（设定 spiky）+ 黑框眼镜（设定 glasses）、白色挂脖耳机；青绿卫衣（设定衣服色）+ 牛仔裤 + 白球鞋。'},
  'chi-lun':{id:'chi-lun',name:'齿轮',skin:'#e8b98f',body:{type:'bulky',head:'square',sit:'relaxed'},hair:{style:'tidy',color:'#1f1b24'},
    face:{eyes:'sleepy',iris:'#4a4a50',brows:'straight',mouth:'flat'},
    top:{kind:'tee',color:'#3a3f48'},outer:{kind:'zip',color:'#66707d'},bottom:{kind:'jeans',color:'#3a3f48'},shoes:{kind:'sneakers',color:'#66707d'},acc:[{kind:'headphones',color:'#d4b04c'},{kind:'pin',color:'#d4b04c',shape:'gear'}],
    tendency:{expression:'neutral',gesture:.7,lean:-.04,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:C,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'后端工程师、数据洁癖：短发（设定）、睡眼（设定 sleepy）；灰色拉链卫衣（设定衣服色）+ 深色 T + 牛仔裤，一副金色头戴耳机（设定 accent 金）——闷头写接口的样子。'},
  'tiao-se-pan':{id:'tiao-se-pan',name:'调色盘',skin:'#f3d2b3',body:{type:'cute',head:'round',sit:'side'},hair:{style:'twintails',color:'#7a3b2e',tie:'#3a4a6a'},
    face:{eyes:'sparkle',iris:'#3f7a8a',brows:'arched',mouth:'cat',marks:['blush','freckles']},
    top:{kind:'tee',color:'#f4efe4',pattern:'stripe'},outer:{kind:'apron',color:'#e08a3c'},bottom:{kind:'pants',color:'#3a4a6a'},shoes:{kind:'sneakers',color:'#e08a3c'},acc:[{kind:'beret',color:'#3a4a6a'},{kind:'clip',color:'#e04a6a',side:-1},{kind:'charm',color:'#e08a3c',shape:'palette'}],
    tendency:{expression:'happy',gesture:1.2,lean:.06,tilt:.1},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'UI 设计师，“我出几个方向”：设定的 long 做成红棕双马尾（扎藏青发圈）+ 藏青贝雷帽（和裤子同色）、一枚玫红发夹；橙色画画用的罩衫围裙（设定衣服色）+ 条纹 T；亮眼、猫嘴、腮红（设定 blush）和雀斑。配色是全员最跳的。'},
  'bu-chong-wang':{id:'bu-chong-wang',name:'捕虫网',skin:'#f1c9a5',body:{type:'outdoor',sit:'standard'},hair:{style:'curtain',color:'#3d3550'},
    face:{eyes:'round',iris:'#4a6a2a',brows:'arched',mouth:'grin'},
    top:{kind:'tee',color:'#f4efe4'},outer:{kind:'vest',color:'#9cb33e'},bottom:{kind:'shorts',color:'#3d3550',socks:'#f4efe4'},shoes:{kind:'boots',color:'#4a4a3a'},acc:[{kind:'watch'},{kind:'goggles',color:'#4a4a3a'}],
    tendency:{expression:'happy',gesture:1.15,lean:.08,tilt:.06},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:C,shoes:I,acc:I,palette:C,tendency:C},
    why:'测试工程师、边界狂魔：中分（设定 middle）、挑眉、露齿笑（设定 grin）；草绿多口袋马甲（设定衣服色）+ 短裤 + 长袜 + 短靴，像去野外捉虫。'},
  'mie-huo-qi':{id:'mie-huo-qi',name:'灭火器',skin:'#e8b98f',body:{type:'broad',head:'square',sit:'standard'},hair:{style:'crew',color:'#2b2136'},
    face:{eyes:'round',iris:'#5a2a22',brows:'worried',mouth:'flat',marks:['sweat']},
    top:{kind:'tee',color:'#e9e1c8'},outer:{kind:'jacket',color:'#c4473f',trim:'#e9e1c8'},bottom:{kind:'cargo',color:'#3a3a40'},shoes:{kind:'boots',color:'#2a2a2a'},acc:[{kind:'cap',color:'#c4473f'},{kind:'tool',color:'#c4473f',shape:'extinguisher'}],
    tendency:{expression:'neutral',gesture:1.1,lean:.1,tilt:0},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'运维，半夜负责救火：设定的 cap（红）+ 寸头、汗（设定 sweat）、八字眉；红色值班夹克（设定衣服色）罩米白 T 恤（设定 accent 色）+ 工装裤 + 黑靴。'},
  'la-ba':{id:'la-ba',name:'喇叭',skin:'#f6d7bd',body:{type:'standard',head:'round',sit:'side'},hair:{style:'curly',color:'#5a3a2a'},
    face:{eyes:'sparkle',iris:'#8a3a6a',brows:'arched',mouth:'smile'},
    top:{kind:'tee',color:'#f4efe4'},outer:{kind:'varsity',color:'#a8458a',trim:'#f4d35e'},bottom:{kind:'skirt',color:'#3a2a3a',socks:'#f4efe4'},shoes:{kind:'sneakers',color:'#f4efe4'},acc:[{kind:'bow',color:'#f4d35e',side:1},{kind:'pin',color:'#a8458a',shape:'megaphone'}],
    tendency:{expression:'happy',gesture:1.35,lean:.1,tilt:.08},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:C},
    why:'运营，帮你吆喝：卷发（设定 curly）+ 黄色大发结、亮眼、笑（设定 happy）；紫红棒球服（设定衣服色）+ 百褶裙 + 长袜——最外向的一身，手势全员最大。'},
  'gang-bi':{id:'gang-bi',name:'钢笔',skin:'#f3d2b3',body:{type:'longcoat',head:'long',sit:'standard'},hair:{style:'sweep',color:'#2b2136'},
    face:{eyes:'droopy',iris:'#5a3a2a',brows:'soft',mouth:'smile'},
    top:{kind:'shirt',color:'#f2ece0'},outer:{kind:'cardigan',color:'#8b5e3c',trim:'#e9e1c8'},bottom:{kind:'pants',color:'#34405a'},shoes:{kind:'loafers',color:'#2a2020'},acc:[{kind:'scarf',color:'#e9e1c8'},{kind:'pen',color:'#2b2136',side:1},{kind:'pin',color:'#8b5e3c',shape:'scroll'}],
    tendency:{expression:'neutral',gesture:.9,lean:.04,tilt:.06},
    basis:{skin:C,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:C,palette:C,tendency:C},
    why:'文案，大白话、有温度：侧分（设定 side）、温和的下垂眼；米白围巾（设定 scarf + accent 色）、棕色开衫（设定衣服色）、墨水蓝长裤、耳后一支钢笔——文气。'},
  // ———— 理性辩论组（visual 是 rationalPersonas.ts 轮换后的实际值） ————
  'math-intuitionist-001':{id:'math-intuitionist-001',name:'阿澜',skin:'#f4d2b0',body:{type:'standard',sit:'relaxed'},hair:{style:'tidy',color:'#2b2136'},
    face:{eyes:'sparkle',iris:'#2f6f8a',brows:'soft',mouth:'smile'},
    top:{kind:'shirt',color:'#f4f0e8'},outer:{kind:'vest',color:'#4F9DB8'},bottom:{kind:'pants',color:'#3a3f4a'},shoes:{kind:'sneakers',color:'#f0eee8'},acc:[{kind:'ahoge'},{kind:'pin',color:'#4F9DB8',shape:'sigma'}],
    tendency:{expression:'neutral',gesture:1.1,lean:.06,tilt:.05},
    basis:{skin:R,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:I},
    why:'直觉派数学教育者，“先给一个画面”：短发（设定）+ 一根呆毛（直觉的灵光）、亮晶晶的眼、浅笑；水蓝毛线马甲（设定衣服色）+ 白衬衫，像会在黑板前画图的老师。 肤色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'skeptic-001':{id:'skeptic-001',name:'灰先生',skin:'#8d6a52',body:{type:'longcoat',head:'long',sit:'relaxed'},hair:{style:'lowtail',color:'#6b4a3a',tie:'#3a3a40'},
    face:{eyes:'narrow',iris:'#5a5a60',brows:'arched',mouth:'smirk'},
    top:{kind:'turtleneck',color:'#3a3a40'},outer:{kind:'coat',color:'#8A8F96',trim:'#5a5f66'},bottom:{kind:'pants',color:'#2e2e34'},shoes:{kind:'loafers',color:'#2a2a2a'},acc:[{kind:'monocle',color:'#8A8F96'}],
    tendency:{expression:'neutral',gesture:.8,lean:-.06,tilt:.05},
    basis:{skin:R,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:I},
    why:'怀疑者、认识论研究者，“凭什么认为它成立”：设定的 long 做成后梳的低马尾（垂到背上）；细长眼、一边眉挑着、似笑非笑；灰色长风衣（设定衣服色）+ 深色高领，往后靠着看人。 肤色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'socratic-questioner-001':{id:'socratic-questioner-001',name:'老苏',skin:'#e0c4a8',body:{type:'bulky',head:'round',sit:'standard'},hair:{style:'topknot',color:'#6b6272'},
    face:{eyes:'droopy',iris:'#4a4a6a',brows:'thick',mouth:'small'},
    top:{kind:'sweater',color:'#e9e4d8',trim:'#7A6FB0'},outer:{kind:'cardigan',color:'#7A6FB0',trim:'#e9e4d8'},bottom:{kind:'pants',color:'#4a4458'},shoes:{kind:'loafers',color:'#3a3040'},acc:[{kind:'beard',color:'#8a8290'},{kind:'pin',color:'#7A6FB0',shape:'therefore'}],
    tendency:{expression:'thinking',gesture:.9,lean:.08,tilt:.08},
    basis:{skin:R,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:I},
    why:'追问者、哲学对话者（“老”苏、苏格拉底式）：灰发头顶扎一个发髻（设定 bun）+ 一把灰胡子、粗眉、下垂的眼；紫色长开衫（设定衣服色）罩米色毛衣。默认表情是在想，前倾追问。 肤色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'pragmatic-philosopher-001':{id:'pragmatic-philosopher-001',name:'南姐',skin:'#b57a56',body:{type:'outdoor',sit:'standard'},hair:{style:'ponytail',color:'#3d3550',tie:'#C07A5A'},
    face:{eyes:'round',iris:'#6a4a3a',brows:'straight',mouth:'smile'},
    top:{kind:'tee',color:'#f2ece0'},outer:{kind:'jacket',color:'#C07A5A',trim:'#7a4a32'},bottom:{kind:'jeans',color:'#3a4a6a'},shoes:{kind:'boots',color:'#7a6646'},acc:[{kind:'cap',color:'#8a7a52'},{kind:'waistBag',color:'#C07A5A'}],
    tendency:{expression:'neutral',gesture:1.05,lean:.08,tilt:0},
    basis:{skin:R,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:C,palette:C,tendency:I},
    why:'现实派、社工与应用伦理研究者，“对具体的人有什么影响”：设定的 cap 保留，做成卡其色帆布帽（和深色头发分开），马尾从帽子后面穿出来；陶土色工作夹克（设定衣服色）+ 牛仔裤 + 和帽子同色系的棕黄短靴——跑社区的实干派。 肤色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
  'logic-analyst-001':{id:'logic-analyst-001',name:'K',skin:'#d8b89a',body:{type:'crisp',head:'square',sit:'standard'},hair:{style:'crew',color:'#8a5a3c'},
    face:{eyes:'narrow',iris:'#3a4a5a',brows:'straight',mouth:'flat'},
    top:{kind:'turtleneck',color:'#e9e6e0'},outer:{kind:'blazer',color:'#5A6B7D',trim:'#e9e6e0'},bottom:{kind:'pants',color:'#2e3640'},shoes:{kind:'loafers',color:'#20242a'},acc:[{kind:'glasses',color:'#20242a'},{kind:'pin',color:'#5A6B7D',shape:'ruler'}],
    tendency:{expression:'neutral',gesture:.8,lean:0,tilt:0},
    basis:{skin:R,body:I,hairColor:C,hairStyle:C,eyes:I,top:I,outer:C,bottom:I,shoes:I,acc:I,palette:C,tendency:I},
    why:'逻辑家，“逐步检查”：极短的寸头（设定 short、栗色）、方框眼镜、细长眼、平眉；石板灰西装（设定衣服色）+ 浅色高领，一丝不苟，手势最少。 肤色没有写在人物文件里，按多种族、不要同一个模子的要求拉开。'},
};
