import {useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {McStage3D} from '../components/McStage3D';
import {RATIONAL_PERSONAS} from '../data/rationalPersonas';
import {LIBRARY_PERSONAS} from '../data/personas';
import {debateSchedule} from '../engines/rational/schedule';
import type {EngineEvent,Participant,SessionConfig,ChatMessage,MindView} from '../types';
import type {DirectorState} from '../mc/director';
import type {McStageProps} from '../components/McStage3D';
import '../styles.css';
const people=[...RATIONAL_PERSONAS,...LIBRARY_PERSONAS.filter(p=>!RATIONAL_PERSONAS.some(q=>q.id===p.id))].slice(0,7);
const cast:Participant[]=people.map((persona,i)=>({agentId:persona.id,persona,side:i<3?'pro':i<6?'con':'host',seatIndex:i,personalityId:persona.defaultPersonalityId,color:persona.visual.shirt}));
const cfg:SessionConfig={sessionId:'mc-lab',mode:'rational',sceneId:'debate-mc',theme:{title:'人工智能应不应该进入课堂？'},maxRounds:3,maxChars:150,participants:cast,engineOptions:{},createdAt:'2026-10-05'};
let seq=0;const message=(speakerId:string,text:string,extra:Partial<ChatMessage>={}):ChatMessage=>({id:'lab-'+seq++,round:1,speakerId,text,kind:'speech',at:Date.now(),...extra});
function Lab(){
  const [data,setData]=useState<Omit<McStageProps,'onFocus'|'onLoaded'|'onStageDone'>>({events:[],participants:cast,status:{},round:{n:0,label:'准备中'},totalRounds:3,session:'waiting',messages:[],minds:{},focus:null,errors:[],result:null,theme:cfg.theme.title,muted:true});
  const [chosen,setChosen]=useState(cast[0].agentId),[inspect,setInspect]=useState(''),[error,setError]=useState(''),[auto,setAuto]=useState(false),[gallery,setGallery]=useState(false),[stats,setStats]=useState({fps:0,calls:0,loadedMs:0});
  const current=useRef(data);current.current=data;const snapshot=useRef<DirectorState|null>(null),trace=useRef<unknown[]>([]),gates=useRef(new Map<string,()=>void>()),lastStats=useRef(0),cancelled=useRef(false);
  const emit=(event:EngineEvent)=>{trace.current.push({at:performance.now(),event});setData(d=>{d={...d,events:[...(d.events??[]),event]};switch(event.type){case 'session':return {...d,session:event.state};case 'round':return {...d,round:{n:event.round,label:event.label}};case 'status':return {...d,status:{...d.status,[event.agentId]:{state:event.state,action:event.action}}};case 'mind':return {...d,minds:{...d.minds,[event.agentId]:event.mind}};case 'message':return {...d,messages:[...d.messages,event.message]};case 'message_update':return {...d,messages:d.messages.map(m=>m.id===event.id?{...m,text:event.text,cut:event.cut??m.cut}:m)};case 'error':return {...d,errors:[...d.errors,event]};case 'result':return {...d,result:event.result};case 'theme':return {...d,theme:event.title};default:return d;}});};
  const delay=async(ms:number)=>{let time=0;while(time<ms&&!cancelled.current){await new Promise(r=>setTimeout(r,50));if(current.current.session!=='paused')time+=50;}};
  const waitGate=(kind:string,key:string)=>new Promise<void>(resolve=>{gates.current.set(kind+':'+key,resolve);setTimeout(resolve,4500);});
  const speak=async(id=chosen,target?:string,tag='正方一辩 · 立论',text='技术能帮助人学习，但我们也要保留独立思考的空间。')=>{
    emit({type:'status',agentId:id,state:'thinking',action:'组织论点'});await delay(450);
    const ready=waitGate('speech',id);emit({type:'status',agentId:id,state:'speaking',action:tag});await ready;
    const m=message(id,'',{targetId:target,tag,round:current.current.round.n||1});emit({type:'message',message:m});
    for(let i=2;i<=text.length+2;i+=2){emit({type:'message_update',id:m.id,text:text.slice(0,i)});await delay(65);}
    emit({type:'status',agentId:id,state:'idle',action:'倾听'});
  };
  const round=async(n:number,label:string)=>{const ready=waitGate('round',String(n));emit({type:'round',round:n,label});await ready;};
  const mood=(high:boolean,only?:string)=>{const m:MindView={mood:['火气','压力','信心','憋屈'].map((key,i)=>({key,value:only?(key===only?8:0):high?8:key==='信心'?5:3,color:['#FF5555','#FFAA00','#5555FF','#AA00AA'][i]})),label:only??(high?'火力全开':'有点紧'),emoji:'😤',face:only?[]:high?['brows','sweat','blush']:['happy'],inner:'我要把这个问题讲清楚。',stance:'支持有边界地使用技术',plan:'先回应质询，再给出例子',toward:[]};emit({type:'mind',agentId:chosen,mind:m});};
  const result=(verdict:boolean)=>emit({type:'result',result:{summary:'双方围绕学习与独立思考展开讨论。',consensus:['技术应当辅助学习'],disagreements:['使用的边界'],openQuestions:['如何评估效果'],suggestions:['先试点'],...(verdict?{verdict:{winner:'正方',proScore:82,conScore:76,reason:'正方更充分地回答了核心质询。'}}:{})}});
  const automate=async()=>{cancelled.current=false;setAuto(true);emit({type:'session',state:'running'});let lastRound=0;for(const turn of debateSchedule(cfg)){if(cancelled.current)break;if(turn.round!==lastRound){lastRound=turn.round;await round(turn.round,turn.stage);}await speak(turn.speaker.agentId,turn.target?.agentId,turn.tag);await delay(300);}if(!cancelled.current){result(true);emit({type:'session',state:'finished'});}setAuto(false);};
  const actions:Array<[string,()=>void]>=[['开场',()=>emit({type:'session',state:'running'})],['立论',()=>void round(1,'立论陈述')],['交锋',()=>void round(2,'交锋质询')],['总结',()=>void round(3,'总结陈词')],['思考',()=>emit({type:'status',agentId:chosen,state:'thinking',action:'组织论点'})],['开始发言',()=>emit({type:'status',agentId:chosen,state:'speaking',action:'正方一辩 · 立论'})],['说一句',()=>void speak()],['说长句',()=>void speak(chosen,undefined,'正方一辩 · 立论','我们需要仔细讨论这个问题，因为教育的目的不仅是提高答题速度，还包括好奇心、判断力、交流能力和责任感。人工智能可以帮助老师发现每个学生的困难，也可能让人跳过探索和试错。应当设定清楚的边界，并且保留亲自练习、独立作答以及讨论不同意见的机会。')],['说完',()=>emit({type:'status',agentId:chosen,state:'idle',action:'倾听'})],['交锋一对',()=>void (async()=>{await round(2,'交锋质询');await speak(cast[0].agentId,cast[3].agentId,'正方一辩 · 交锋');})()],['下一对',()=>void speak(cast[1].agentId,cast[4].agentId,'正方二辩 · 交锋')],['打断',()=>{const m=current.current.messages.filter(m=>m.speakerId===chosen).at(-1);if(m)emit({type:'message_update',id:m.id,text:m.text.slice(0,12),cut:true});}],['公开插话',()=>emit({type:'message',message:message('user','请双方举一个具体的例子。',{kind:'user'})})],['悄悄话',()=>emit({type:'message',message:message('user','请关注学生的独立思考。',{kind:'user',private:true,targetId:chosen})})],['私聊回复',()=>emit({type:'message',message:message(chosen,'明白，我会把这点纳入下一句。',{kind:'reply',private:true,targetId:'user'})})],['情绪第一档',()=>mood(false)],['情绪第二档',()=>mood(true)],['成员掉线',()=>emit({type:'error',id:'lab-error',agentId:chosen,message:'连接暂时不可用'})],['恢复',()=>{setData(d=>({...d,errors:[]}));emit({type:'status',agentId:chosen,state:'idle',action:'倾听'});}],['整场出错',()=>emit({type:'error',id:'global-error',message:'服务暂时无法连接'})],['暂停',()=>emit({type:'session',state:'paused'})],['继续',()=>emit({type:'session',state:'running'})],['判定结果',()=>{result(true);emit({type:'session',state:'finished'});}],['无判定结果',()=>{result(false);emit({type:'session',state:'finished'});}],['换辩题',()=>emit({type:'theme',title:'城市应不应该限制私家车？'})],['点选成员',()=>setData(d=>({...d,focus:d.focus===chosen?null:chosen}))],['自动演一场',()=>void automate()],['停止',()=>{cancelled.current=true;emit({type:'session',state:'stopped'});}]];
  actions.push(...['火气','压力','信心','憋屈'].map(key=>[key+'姿态',()=>mood(true,key)] as [string,()=>void]));
  if(import.meta.env.DEV)(window as unknown as {__mcLab:unknown}).__mcLab={get snapshot(){return snapshot.current;},get trace(){return trace.current;},get stats(){return stats;},emit,speak,round,result,mood,automate,cast};
  return <main className="mc-lab"><header><h1>我的世界辩论室</h1><p>查看舞台动作与信息展示</p><span>{stats.fps.toFixed(0)} 帧 / 秒 · {stats.calls} 次绘制 · 加载 {stats.loadedMs.toFixed(0)} 毫秒</span></header><div className="mc-lab-layout"><section className="mc-lab-stage"><McStage3D material={(['original','hd','style'] as const).find(x=>x===new URLSearchParams(location.search).get('material'))} {...data} inspect={inspect} inspectActor={chosen} gallery={gallery} onFocus={focus=>setData(d=>({...d,focus}))} onLoaded={e=>setError(e??'')} onStageDone={(kind,key)=>{trace.current.push({at:performance.now(),done:{kind,key}});const id=kind+':'+key;gates.current.get(id)?.();gates.current.delete(id);}} onSnapshot={(s,o,stats)=>{snapshot.current=s;for(const a of o.actions)trace.current.push({stage:s.now,action:a});if(performance.now()-lastStats.current>1000){lastStats.current=performance.now();setStats(stats);}}}/>{error&&<p className="mc-lab-error">{error}</p>}</section><aside className="mc-lab-controls"><label>操作的人物<select value={chosen} onChange={e=>setChosen(e.target.value)}>{cast.map(p=><option key={p.agentId} value={p.agentId}>{p.persona.name}</option>)}</select></label><label>物品近景<select value={inspect} onChange={e=>setInspect(e.target.value)}><option value="">舞台</option><option value="table">辩论桌与人物</option><option value="chair">会议椅与人物</option><option value="lever">拉杆和红石灯</option><option value="podium">讲台、讲稿与主持</option><option value="bell">桌铃</option><option value="board">辩题板</option><option value="front">辩题板与讲台</option><option value="book">书与笔</option><option value="judge">评委桌椅</option></select></label><label><input type="checkbox" checked={gallery} onChange={e=>setGallery(e.target.checked)}/> 方块陈列</label><label><input type="checkbox" checked={!data.muted} onChange={e=>setData(d=>({...d,muted:!e.target.checked}))}/> 打开音效</label><div>{actions.map(([name,fn])=><button className="mc-button" key={name} disabled={auto&&name==='自动演一场'} onClick={fn}>{name}</button>)}</div><button className="mc-button" onClick={()=>location.reload()}>重新开始</button></aside></div></main>;
}
createRoot(document.getElementById('root')!).render(<Lab/>);
